//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElapsoApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElapsoContext : DbContext
    {
        public ElapsoContext()
            : base("name=ElapsoContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ElapsoBaseClass> ElapsoBaseClassSet { get; set; }

        public System.Data.Entity.DbSet<ElapsoApp.Models.Counter> Counters { get; set; }

        public System.Data.Entity.DbSet<ElapsoApp.Models.Comment> Comments { get; set; }
    }
}
